title: "Project CPP 528"
author: "Caitlyn McCullers, Sarah Johaningsmeir, Ahmed Radwan, Mohamed Said"
description: "This site hosts our final project for CPP 528!"

# Jekyll settings
permalink: /:title/          # see https://jekyllrb.com/docs/permalinks/
paginate: 2                  # number of articles per page, remove to disable pagination
excerpt_separator: "\n\n\n"  # indicates the end of the excerpt by two blank lines

# Theme settings
show_excerpts: false         # show article previews on the home page instead of headlines
date_format: "%B %d, %Y"     # see http://shopify.github.io/liquid/filters/date/
dark_theme: true             # enables dark mode
dark_header: false           # uses dark header whether dark_theme is enabled or not
minimal_theme: true          # radically minimalistic theme

navigation:                  # show navigation links in the header	
  - index.md  # Landing page with Table of Contents
  - about.md
  - resources.md
  - README.md
  
icons:                       # show icons in the header, for all possible icons see http://fontawesome.io/icons/
  # envelope: "mailto:niklasbuschmann@users.noreply.github.com"
  # github: "https://github.com/R-Class/cpp-528-template/edit/main/"
  
  
comments:                    # embed disqus or isso comments
#  disqus: "disqus-contrast"
#  isso: "comments.mysite.org"

remote_theme: niklasbuschmann/contrast

plugins: 
 - jekyll-remote-theme
 - jekyll-feed
 - jekyll-paginate
 - jekyll-default-layout

theme: jekyll-theme-architect

# For any extra visual customization, you can include additional CSS files in every page on your site. List any custom CSS files here
#site-css:
# - "/assets/css/style.scss"

# Personalize the colors in your website. Colour values can be any valid CSS colour

navbar-col: "#373C99"
navbar-text-col: "#91A7FE"
navbar-children-col: "#FE9D8D"
page-col: "#FDECBE"
link-col: "EB6B78"
hover-col: "#FE9D8D"
footer-col: "#F5F5F5"
footer-text-col: "#373C99"
footer-link-col: "#91A7FE"
